### ISSUE TITLE
Can i contact you for help on my project?

### ISSUE THREAD

**Issue by jvmoraiscb** [kbogert/falconunity#10]
Hello! My name is João and i am a brazilian computer engineering student!

I am currently starting a project using novint falcon, i know this repository was made a long time ago, but i am having some difficulties and would like to know if there is any way i can contact you (email, social network, linkedin, discord, anything).

Have a good day,
jvmoraiscb

**Comment by kbogert** [comment]
Hi João,

You can contact me at kbogert@unca.edu
