### ISSUE TITLE
Get constant force

### ISSUE THREAD

**Issue by foeser** [kbogert/falconunity#3]
Hello again :)

I set a ForceField to the Falcon via "setForceField(falcon_num,new Vector3(0,0,-10));". So i have a constant pressure on the z axis. When i now push against the grip i like to get the constant force even when i don't move forward directly (just pushing with a constant force against the pressure, you know?). I tried "getAverageFalconForces(falcon_num, out forces);". Then i get a force of 10 on the z axis (without touching the grip). When i now push against the grip and press it to the body the value increases. So far so good. But when i just press/push so much that i don't move the grip directly further i get the value of 10 again. But i still press. It's hard to explain, do you know what i mean? I like to know i fthe user presses with a constant force even when the grip is then not moving forwards.

Thanks a lot for you help.

**Comment by rsilva56** [comment]
Hello is this project still alive?

**Comment by kbogert** [comment]
I'm not actively working on the project at the moment, though I will support it as best I can.

**Comment by rsilva56** [comment]
trying to get It working with unity 5.3 free. is this possible? Do I still need to use the falcon server?

**Comment by kbogert** [comment]
Please open a new issue if falconunity does not work in 5.3
