### ISSUE TITLE
Force tip to move at center 

### ISSUE THREAD

**Issue by aliBUT** [kbogert/falconunity#6]
is it possible to snap the tip to the center of the haptic controller? if yes any idea how?

**Comment by kbogert** [comment]
Yes, set the god object's mass to zero, then move it to where you want it.

**Comment by aliBUT** [comment]
Hi @kbogert thank you for this suggestion but is there any other way to make it center? if I make god object mass zero the tip become very hard to move. i want to make the tip center when application starts and when no one uses it for few seconds
