### ISSUE TITLE
Stop the object when it is no longer pushed by the falcon

### ISSUE THREAD

**Issue by gabrielgriesser** [kbogert/falconunity#7]
When I push an object with my Falcon, the object moves forward and I feel the force feedback. But when I stop pushing it, the object keeps moving forward indefinitely and never stops as if it were in space. Also, it passes through all the other objects in the scene....

How to solve this problem?

**Comment by kbogert** [comment]
All physics objects that can interact with the falcon or each other must be
imported into falconunity.

I'm not sure what you are looking for in terms of the object's movement,
physics engines pretty much simulate a bunch of ridged balls moving through
space:

Are you looking for gravity? You can set that in the FalconMain component.

You want the object to return to it's original position after being pushed?
Use the FalconSpringedBody script.

You want the object to freeze in place the moment the falcon tip loses
contact? This is more difficult than it sounds, but you can write a script
which will call setDynamicShapePose() within FalconUnity.cs giving it the
current pose of the object, which will reset its velocity. You could do
this so long as the tip is at least a safe distance away from the object.
Be aware that the physics world is updated much much faster than the
graphics one, so you'll have to give the script a wide margin of error to
avoid breaking the physics sim in the case of really fast movement.

A safer approach would be to write your own controller, like PID controller
for instance, that produces the behavior you want and have it call
applyForce() in FalconUnity.cs to manually move the object.

**Comment by gabrielgriesser** [comment]
Hello,

Thank you so mush for you fast answer.
I took a little video capture to show you my problem. 
You see, objects never stop moving forward, as if the force were continuously applied.
https://streamable.com/76mw0

**Comment by kbogert** [comment]
The object continues at constant velocity, because no forces are being
applied to it. This is correct behavior.  If you want it to stop you'll
have to use one of the solutions I gave you above.

See: https://youtu.be/kKKM8Y-u7ds
