### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by ztdn-0311** [kbogert/falconunity#9]
Hi, do you know where is located the .unitypackage? I have troubles loading the plugin from github, do you have any guide I could follow? I would appreciate it so much

**Comment by kbogert** [comment]
The .unitypackage is located in the release zip file, https://github.com/kbogert/falconunity/releases/tag/v0.22

Follow the Quick Setup section of the README.md instructions https://github.com/kbogert/falconunity/blob/master/README.md to get your project working with the falcon.
